# ====== 数据集配置 ======
dataset: correlate_data
#data_dir: synthetic_datasets
data_file: dataset/correlate_data.npz # SYN-C1 数据路径
#scaler: StandardScaler
correlation_threshold: 0.075
# ====== 训练配置 ======
batch_size: 6 # SYN-C1 有 5000 样本，batch_size 可以适中
seeds: 10 # 运行 3 次不同随机种子
validate: true  # 开启验证

# ====== 训练轮数 ======
epochs: &epochs 1287
ae_non_gated_epochs: 58  # 前 10 个 epoch 不启用门控
ae_pretrain_epochs: 594 # 前 100 个 epoch 预训练 Encoder-Decoder
start_global_gates_training_on_epoch: 812  # 从第 150 个 epoch 开始训练全局门控

# ====== 数据增强 ======
mask_percentage: 0.63 # 随机 mask 90% 的特征
latent_noise_std: 0.01  # 隐藏层噪声标准差

# ====== PyTorch Lightning Trainer 配置 ======
trainer:
  devices: 1
  accelerator: gpu  # 如果没有 GPU，改为 cpu
  max_epochs: *epochs
  deterministic: true
  logger: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10  # 每 10 个 epoch 验证一次
  enable_checkpointing: false
  num_sanity_val_steps: 0

# ====== GTCR 损失（Total Coding Rate）======
gtcr_loss: true
#gtcr_projection_dim: 256
gtcr_projection_dim: null
gtcr_eps: 1
gtcr_lambda: 0.033  # GTCR 损失权重

# ====== MCRR 损失（Maximal Coding Rate Reduction）======
#eps: 0.1  # MCRR 的 epsilon #eps: 0.01
eps: 0.35
# ====== 门控网络配置 ======
use_gating: true
gates_hidden_dim: 120 # 门控网络隐藏层维度（根据特征数调整）#512

# ====== Encoder-Decoder 架构 ======
encdec:
  - 512   # 第一层：500 → 256
  - 512   # 第二层
  - 2048   # 第三层
  - &bn_layer 32  # 瓶颈层（Bottleneck）：最小维度
  - 2048   # 解码器第一层
  - 512   # 解码器第二层
  - 512   # 解码器第三层：256 → 500

# ====== 聚类头 ======
clustering_head:
  - *bn_layer  # 输入：64（瓶颈层）
  - 128      # 隐藏层

# ====== Gumbel-Softmax 温度 ======
tau: 60
sefs_tau: 1.29

# ====== 辅助分类器 ======
aux_classifier:
  - 128

# ====== 损失权重 ======
local_gates_lambda: 1.21
global_gates_lambda: 0.0002


# ====== 学习率配置 ======
lr:
  pretrain: 8e-4   # 预训练学习率
  clustering: 4e-3   # 聚类学习率
  aux_classifier: 1e-4 # 辅助分类器学习率

# ====== 学习率调度器 ======
sched:
  pretrain_min_lr: 2e-5    # 预训练最小学习率
  clustering_min_lr: 5e-7  # 聚类最小学习率

# ====== 保存检查点 ======
save_seed_checkpoints: false  # 保存最佳模型-*
# ====== 早停配置 ======
#early_stop_patience: 30      # 连续 30 个验证周期（= 300 epoch）无改善则停止
                             # 每 10 epoch 验证一次（check_val_every_n_epoch: 10）
                             # 30 × 10 = 300 epoch 的容忍窗口
use_sefs: true    # ✅ IDC + SEFS（相关噪声）
#use_sefs: false # ✅ 切换为 IDC 原版（独立高斯噪声）